/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CredenciamentoRouteImport } from './routes/credenciamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotoristaIndexRouteImport } from './routes/motorista/index'
import { Route as GestorIndexRouteImport } from './routes/gestor/index'
import { Route as FornecedorIndexRouteImport } from './routes/fornecedor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MotoristaViagemRouteImport } from './routes/motorista/viagem'
import { Route as MotoristaSolicitarRouteImport } from './routes/motorista/solicitar'
import { Route as MotoristaNotificacoesRouteImport } from './routes/motorista/notificacoes'
import { Route as MotoristaIniciarJornadaRouteImport } from './routes/motorista/iniciar-jornada'
import { Route as MotoristaHistoricoRouteImport } from './routes/motorista/historico'
import { Route as MotoristaFotoRouteImport } from './routes/motorista/foto'
import { Route as MotoristaEncerrarJornadaRouteImport } from './routes/motorista/encerrar-jornada'
import { Route as MotoristaChecklistRouteImport } from './routes/motorista/checklist'
import { Route as MotoristaAbastecimentoRouteImport } from './routes/motorista/abastecimento'
import { Route as GestorVeiculosRouteImport } from './routes/gestor/veiculos'
import { Route as GestorMotoristasRouteImport } from './routes/gestor/motoristas'
import { Route as GestorManutencoesRouteImport } from './routes/gestor/manutencoes'
import { Route as FornecedorSolicitacoesRouteImport } from './routes/fornecedor/solicitacoes'
import { Route as FornecedorServicosRouteImport } from './routes/fornecedor/servicos'
import { Route as FornecedorServicoRouteImport } from './routes/fornecedor/servico'
import { Route as FornecedorPerfilRouteImport } from './routes/fornecedor/perfil'
import { Route as FornecedorOrcamentosRouteImport } from './routes/fornecedor/orcamentos'
import { Route as FornecedorOrcamentoRouteImport } from './routes/fornecedor/orcamento'
import { Route as FornecedorLancarPecasRouteImport } from './routes/fornecedor/lancar-pecas'
import { Route as FornecedorHistoricoRouteImport } from './routes/fornecedor/historico'
import { Route as FornecedorFinanceiroRouteImport } from './routes/fornecedor/financeiro'
import { Route as FornecedorDespesaRouteImport } from './routes/fornecedor/despesa'
import { Route as FornecedorAbastecerRouteImport } from './routes/fornecedor/abastecer'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminFinanceiroContratualRouteImport } from './routes/admin/financeiro-contratual'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AbastecerVeiculoIdRouteImport } from './routes/abastecer.$veiculoId'
import { Route as GestorVeiculosVeiculoIdRouteImport } from './routes/gestor/veiculos.$veiculoId'
import { Route as AdminFinanceiroFornecedoresRouteImport } from './routes/admin/financeiro.fornecedores'
import { Route as AdminClientesEmpresaIdRouteImport } from './routes/admin/clientes.$empresaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CredenciamentoRoute = CredenciamentoRouteImport.update({
  id: '/credenciamento',
  path: '/credenciamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaIndexRoute = MotoristaIndexRouteImport.update({
  id: '/motorista/',
  path: '/motorista/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorIndexRoute = GestorIndexRouteImport.update({
  id: '/gestor/',
  path: '/gestor/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIndexRoute = FornecedorIndexRouteImport.update({
  id: '/fornecedor/',
  path: '/fornecedor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaViagemRoute = MotoristaViagemRouteImport.update({
  id: '/motorista/viagem',
  path: '/motorista/viagem',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaSolicitarRoute = MotoristaSolicitarRouteImport.update({
  id: '/motorista/solicitar',
  path: '/motorista/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaNotificacoesRoute = MotoristaNotificacoesRouteImport.update({
  id: '/motorista/notificacoes',
  path: '/motorista/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaIniciarJornadaRoute = MotoristaIniciarJornadaRouteImport.update({
  id: '/motorista/iniciar-jornada',
  path: '/motorista/iniciar-jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaHistoricoRoute = MotoristaHistoricoRouteImport.update({
  id: '/motorista/historico',
  path: '/motorista/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaFotoRoute = MotoristaFotoRouteImport.update({
  id: '/motorista/foto',
  path: '/motorista/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaEncerrarJornadaRoute =
  MotoristaEncerrarJornadaRouteImport.update({
    id: '/motorista/encerrar-jornada',
    path: '/motorista/encerrar-jornada',
    getParentRoute: () => rootRouteImport,
  } as any)
const MotoristaChecklistRoute = MotoristaChecklistRouteImport.update({
  id: '/motorista/checklist',
  path: '/motorista/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaAbastecimentoRoute = MotoristaAbastecimentoRouteImport.update({
  id: '/motorista/abastecimento',
  path: '/motorista/abastecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorVeiculosRoute = GestorVeiculosRouteImport.update({
  id: '/gestor/veiculos',
  path: '/gestor/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorMotoristasRoute = GestorMotoristasRouteImport.update({
  id: '/gestor/motoristas',
  path: '/gestor/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorManutencoesRoute = GestorManutencoesRouteImport.update({
  id: '/gestor/manutencoes',
  path: '/gestor/manutencoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorSolicitacoesRoute = FornecedorSolicitacoesRouteImport.update({
  id: '/fornecedor/solicitacoes',
  path: '/fornecedor/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorServicosRoute = FornecedorServicosRouteImport.update({
  id: '/fornecedor/servicos',
  path: '/fornecedor/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorServicoRoute = FornecedorServicoRouteImport.update({
  id: '/fornecedor/servico',
  path: '/fornecedor/servico',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorPerfilRoute = FornecedorPerfilRouteImport.update({
  id: '/fornecedor/perfil',
  path: '/fornecedor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorOrcamentosRoute = FornecedorOrcamentosRouteImport.update({
  id: '/fornecedor/orcamentos',
  path: '/fornecedor/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorOrcamentoRoute = FornecedorOrcamentoRouteImport.update({
  id: '/fornecedor/orcamento',
  path: '/fornecedor/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorLancarPecasRoute = FornecedorLancarPecasRouteImport.update({
  id: '/fornecedor/lancar-pecas',
  path: '/fornecedor/lancar-pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorHistoricoRoute = FornecedorHistoricoRouteImport.update({
  id: '/fornecedor/historico',
  path: '/fornecedor/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorFinanceiroRoute = FornecedorFinanceiroRouteImport.update({
  id: '/fornecedor/financeiro',
  path: '/fornecedor/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorDespesaRoute = FornecedorDespesaRouteImport.update({
  id: '/fornecedor/despesa',
  path: '/fornecedor/despesa',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorAbastecerRoute = FornecedorAbastecerRouteImport.update({
  id: '/fornecedor/abastecer',
  path: '/fornecedor/abastecer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroContratualRoute =
  AdminFinanceiroContratualRouteImport.update({
    id: '/admin/financeiro-contratual',
    path: '/admin/financeiro-contratual',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecerVeiculoIdRoute = AbastecerVeiculoIdRouteImport.update({
  id: '/abastecer/$veiculoId',
  path: '/abastecer/$veiculoId',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorVeiculosVeiculoIdRoute = GestorVeiculosVeiculoIdRouteImport.update({
  id: '/$veiculoId',
  path: '/$veiculoId',
  getParentRoute: () => GestorVeiculosRoute,
} as any)
const AdminFinanceiroFornecedoresRoute =
  AdminFinanceiroFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AdminFinanceiroRoute,
  } as any)
const AdminClientesEmpresaIdRoute = AdminClientesEmpresaIdRouteImport.update({
  id: '/$empresaId',
  path: '/$empresaId',
  getParentRoute: () => AdminClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/login': typeof LoginRoute
  '/abastecer/$veiculoId': typeof AbastecerVeiculoIdRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/financeiro-contratual': typeof AdminFinanceiroContratualRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/fornecedor/abastecer': typeof FornecedorAbastecerRoute
  '/fornecedor/despesa': typeof FornecedorDespesaRoute
  '/fornecedor/financeiro': typeof FornecedorFinanceiroRoute
  '/fornecedor/historico': typeof FornecedorHistoricoRoute
  '/fornecedor/lancar-pecas': typeof FornecedorLancarPecasRoute
  '/fornecedor/orcamento': typeof FornecedorOrcamentoRoute
  '/fornecedor/orcamentos': typeof FornecedorOrcamentosRoute
  '/fornecedor/perfil': typeof FornecedorPerfilRoute
  '/fornecedor/servico': typeof FornecedorServicoRoute
  '/fornecedor/servicos': typeof FornecedorServicosRoute
  '/fornecedor/solicitacoes': typeof FornecedorSolicitacoesRoute
  '/gestor/manutencoes': typeof GestorManutencoesRoute
  '/gestor/motoristas': typeof GestorMotoristasRoute
  '/gestor/veiculos': typeof GestorVeiculosRouteWithChildren
  '/motorista/abastecimento': typeof MotoristaAbastecimentoRoute
  '/motorista/checklist': typeof MotoristaChecklistRoute
  '/motorista/encerrar-jornada': typeof MotoristaEncerrarJornadaRoute
  '/motorista/foto': typeof MotoristaFotoRoute
  '/motorista/historico': typeof MotoristaHistoricoRoute
  '/motorista/iniciar-jornada': typeof MotoristaIniciarJornadaRoute
  '/motorista/notificacoes': typeof MotoristaNotificacoesRoute
  '/motorista/solicitar': typeof MotoristaSolicitarRoute
  '/motorista/viagem': typeof MotoristaViagemRoute
  '/admin/': typeof AdminIndexRoute
  '/fornecedor/': typeof FornecedorIndexRoute
  '/gestor/': typeof GestorIndexRoute
  '/motorista/': typeof MotoristaIndexRoute
  '/admin/clientes/$empresaId': typeof AdminClientesEmpresaIdRoute
  '/admin/financeiro/fornecedores': typeof AdminFinanceiroFornecedoresRoute
  '/gestor/veiculos/$veiculoId': typeof GestorVeiculosVeiculoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/login': typeof LoginRoute
  '/abastecer/$veiculoId': typeof AbastecerVeiculoIdRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/financeiro-contratual': typeof AdminFinanceiroContratualRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/fornecedor/abastecer': typeof FornecedorAbastecerRoute
  '/fornecedor/despesa': typeof FornecedorDespesaRoute
  '/fornecedor/financeiro': typeof FornecedorFinanceiroRoute
  '/fornecedor/historico': typeof FornecedorHistoricoRoute
  '/fornecedor/lancar-pecas': typeof FornecedorLancarPecasRoute
  '/fornecedor/orcamento': typeof FornecedorOrcamentoRoute
  '/fornecedor/orcamentos': typeof FornecedorOrcamentosRoute
  '/fornecedor/perfil': typeof FornecedorPerfilRoute
  '/fornecedor/servico': typeof FornecedorServicoRoute
  '/fornecedor/servicos': typeof FornecedorServicosRoute
  '/fornecedor/solicitacoes': typeof FornecedorSolicitacoesRoute
  '/gestor/manutencoes': typeof GestorManutencoesRoute
  '/gestor/motoristas': typeof GestorMotoristasRoute
  '/gestor/veiculos': typeof GestorVeiculosRouteWithChildren
  '/motorista/abastecimento': typeof MotoristaAbastecimentoRoute
  '/motorista/checklist': typeof MotoristaChecklistRoute
  '/motorista/encerrar-jornada': typeof MotoristaEncerrarJornadaRoute
  '/motorista/foto': typeof MotoristaFotoRoute
  '/motorista/historico': typeof MotoristaHistoricoRoute
  '/motorista/iniciar-jornada': typeof MotoristaIniciarJornadaRoute
  '/motorista/notificacoes': typeof MotoristaNotificacoesRoute
  '/motorista/solicitar': typeof MotoristaSolicitarRoute
  '/motorista/viagem': typeof MotoristaViagemRoute
  '/admin': typeof AdminIndexRoute
  '/fornecedor': typeof FornecedorIndexRoute
  '/gestor': typeof GestorIndexRoute
  '/motorista': typeof MotoristaIndexRoute
  '/admin/clientes/$empresaId': typeof AdminClientesEmpresaIdRoute
  '/admin/financeiro/fornecedores': typeof AdminFinanceiroFornecedoresRoute
  '/gestor/veiculos/$veiculoId': typeof GestorVeiculosVeiculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/login': typeof LoginRoute
  '/abastecer/$veiculoId': typeof AbastecerVeiculoIdRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/financeiro-contratual': typeof AdminFinanceiroContratualRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/fornecedor/abastecer': typeof FornecedorAbastecerRoute
  '/fornecedor/despesa': typeof FornecedorDespesaRoute
  '/fornecedor/financeiro': typeof FornecedorFinanceiroRoute
  '/fornecedor/historico': typeof FornecedorHistoricoRoute
  '/fornecedor/lancar-pecas': typeof FornecedorLancarPecasRoute
  '/fornecedor/orcamento': typeof FornecedorOrcamentoRoute
  '/fornecedor/orcamentos': typeof FornecedorOrcamentosRoute
  '/fornecedor/perfil': typeof FornecedorPerfilRoute
  '/fornecedor/servico': typeof FornecedorServicoRoute
  '/fornecedor/servicos': typeof FornecedorServicosRoute
  '/fornecedor/solicitacoes': typeof FornecedorSolicitacoesRoute
  '/gestor/manutencoes': typeof GestorManutencoesRoute
  '/gestor/motoristas': typeof GestorMotoristasRoute
  '/gestor/veiculos': typeof GestorVeiculosRouteWithChildren
  '/motorista/abastecimento': typeof MotoristaAbastecimentoRoute
  '/motorista/checklist': typeof MotoristaChecklistRoute
  '/motorista/encerrar-jornada': typeof MotoristaEncerrarJornadaRoute
  '/motorista/foto': typeof MotoristaFotoRoute
  '/motorista/historico': typeof MotoristaHistoricoRoute
  '/motorista/iniciar-jornada': typeof MotoristaIniciarJornadaRoute
  '/motorista/notificacoes': typeof MotoristaNotificacoesRoute
  '/motorista/solicitar': typeof MotoristaSolicitarRoute
  '/motorista/viagem': typeof MotoristaViagemRoute
  '/admin/': typeof AdminIndexRoute
  '/fornecedor/': typeof FornecedorIndexRoute
  '/gestor/': typeof GestorIndexRoute
  '/motorista/': typeof MotoristaIndexRoute
  '/admin/clientes/$empresaId': typeof AdminClientesEmpresaIdRoute
  '/admin/financeiro/fornecedores': typeof AdminFinanceiroFornecedoresRoute
  '/gestor/veiculos/$veiculoId': typeof GestorVeiculosVeiculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credenciamento'
    | '/login'
    | '/abastecer/$veiculoId'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/financeiro-contratual'
    | '/admin/relatorios'
    | '/fornecedor/abastecer'
    | '/fornecedor/despesa'
    | '/fornecedor/financeiro'
    | '/fornecedor/historico'
    | '/fornecedor/lancar-pecas'
    | '/fornecedor/orcamento'
    | '/fornecedor/orcamentos'
    | '/fornecedor/perfil'
    | '/fornecedor/servico'
    | '/fornecedor/servicos'
    | '/fornecedor/solicitacoes'
    | '/gestor/manutencoes'
    | '/gestor/motoristas'
    | '/gestor/veiculos'
    | '/motorista/abastecimento'
    | '/motorista/checklist'
    | '/motorista/encerrar-jornada'
    | '/motorista/foto'
    | '/motorista/historico'
    | '/motorista/iniciar-jornada'
    | '/motorista/notificacoes'
    | '/motorista/solicitar'
    | '/motorista/viagem'
    | '/admin/'
    | '/fornecedor/'
    | '/gestor/'
    | '/motorista/'
    | '/admin/clientes/$empresaId'
    | '/admin/financeiro/fornecedores'
    | '/gestor/veiculos/$veiculoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credenciamento'
    | '/login'
    | '/abastecer/$veiculoId'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/financeiro-contratual'
    | '/admin/relatorios'
    | '/fornecedor/abastecer'
    | '/fornecedor/despesa'
    | '/fornecedor/financeiro'
    | '/fornecedor/historico'
    | '/fornecedor/lancar-pecas'
    | '/fornecedor/orcamento'
    | '/fornecedor/orcamentos'
    | '/fornecedor/perfil'
    | '/fornecedor/servico'
    | '/fornecedor/servicos'
    | '/fornecedor/solicitacoes'
    | '/gestor/manutencoes'
    | '/gestor/motoristas'
    | '/gestor/veiculos'
    | '/motorista/abastecimento'
    | '/motorista/checklist'
    | '/motorista/encerrar-jornada'
    | '/motorista/foto'
    | '/motorista/historico'
    | '/motorista/iniciar-jornada'
    | '/motorista/notificacoes'
    | '/motorista/solicitar'
    | '/motorista/viagem'
    | '/admin'
    | '/fornecedor'
    | '/gestor'
    | '/motorista'
    | '/admin/clientes/$empresaId'
    | '/admin/financeiro/fornecedores'
    | '/gestor/veiculos/$veiculoId'
  id:
    | '__root__'
    | '/'
    | '/credenciamento'
    | '/login'
    | '/abastecer/$veiculoId'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/financeiro-contratual'
    | '/admin/relatorios'
    | '/fornecedor/abastecer'
    | '/fornecedor/despesa'
    | '/fornecedor/financeiro'
    | '/fornecedor/historico'
    | '/fornecedor/lancar-pecas'
    | '/fornecedor/orcamento'
    | '/fornecedor/orcamentos'
    | '/fornecedor/perfil'
    | '/fornecedor/servico'
    | '/fornecedor/servicos'
    | '/fornecedor/solicitacoes'
    | '/gestor/manutencoes'
    | '/gestor/motoristas'
    | '/gestor/veiculos'
    | '/motorista/abastecimento'
    | '/motorista/checklist'
    | '/motorista/encerrar-jornada'
    | '/motorista/foto'
    | '/motorista/historico'
    | '/motorista/iniciar-jornada'
    | '/motorista/notificacoes'
    | '/motorista/solicitar'
    | '/motorista/viagem'
    | '/admin/'
    | '/fornecedor/'
    | '/gestor/'
    | '/motorista/'
    | '/admin/clientes/$empresaId'
    | '/admin/financeiro/fornecedores'
    | '/gestor/veiculos/$veiculoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CredenciamentoRoute: typeof CredenciamentoRoute
  LoginRoute: typeof LoginRoute
  AbastecerVeiculoIdRoute: typeof AbastecerVeiculoIdRoute
  AdminClientesRoute: typeof AdminClientesRouteWithChildren
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRouteWithChildren
  AdminFinanceiroContratualRoute: typeof AdminFinanceiroContratualRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  FornecedorAbastecerRoute: typeof FornecedorAbastecerRoute
  FornecedorDespesaRoute: typeof FornecedorDespesaRoute
  FornecedorFinanceiroRoute: typeof FornecedorFinanceiroRoute
  FornecedorHistoricoRoute: typeof FornecedorHistoricoRoute
  FornecedorLancarPecasRoute: typeof FornecedorLancarPecasRoute
  FornecedorOrcamentoRoute: typeof FornecedorOrcamentoRoute
  FornecedorOrcamentosRoute: typeof FornecedorOrcamentosRoute
  FornecedorPerfilRoute: typeof FornecedorPerfilRoute
  FornecedorServicoRoute: typeof FornecedorServicoRoute
  FornecedorServicosRoute: typeof FornecedorServicosRoute
  FornecedorSolicitacoesRoute: typeof FornecedorSolicitacoesRoute
  GestorManutencoesRoute: typeof GestorManutencoesRoute
  GestorMotoristasRoute: typeof GestorMotoristasRoute
  GestorVeiculosRoute: typeof GestorVeiculosRouteWithChildren
  MotoristaAbastecimentoRoute: typeof MotoristaAbastecimentoRoute
  MotoristaChecklistRoute: typeof MotoristaChecklistRoute
  MotoristaEncerrarJornadaRoute: typeof MotoristaEncerrarJornadaRoute
  MotoristaFotoRoute: typeof MotoristaFotoRoute
  MotoristaHistoricoRoute: typeof MotoristaHistoricoRoute
  MotoristaIniciarJornadaRoute: typeof MotoristaIniciarJornadaRoute
  MotoristaNotificacoesRoute: typeof MotoristaNotificacoesRoute
  MotoristaSolicitarRoute: typeof MotoristaSolicitarRoute
  MotoristaViagemRoute: typeof MotoristaViagemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FornecedorIndexRoute: typeof FornecedorIndexRoute
  GestorIndexRoute: typeof GestorIndexRoute
  MotoristaIndexRoute: typeof MotoristaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credenciamento': {
      id: '/credenciamento'
      path: '/credenciamento'
      fullPath: '/credenciamento'
      preLoaderRoute: typeof CredenciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/': {
      id: '/motorista/'
      path: '/motorista'
      fullPath: '/motorista/'
      preLoaderRoute: typeof MotoristaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/': {
      id: '/gestor/'
      path: '/gestor'
      fullPath: '/gestor/'
      preLoaderRoute: typeof GestorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/': {
      id: '/fornecedor/'
      path: '/fornecedor'
      fullPath: '/fornecedor/'
      preLoaderRoute: typeof FornecedorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/viagem': {
      id: '/motorista/viagem'
      path: '/motorista/viagem'
      fullPath: '/motorista/viagem'
      preLoaderRoute: typeof MotoristaViagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/solicitar': {
      id: '/motorista/solicitar'
      path: '/motorista/solicitar'
      fullPath: '/motorista/solicitar'
      preLoaderRoute: typeof MotoristaSolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/notificacoes': {
      id: '/motorista/notificacoes'
      path: '/motorista/notificacoes'
      fullPath: '/motorista/notificacoes'
      preLoaderRoute: typeof MotoristaNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/iniciar-jornada': {
      id: '/motorista/iniciar-jornada'
      path: '/motorista/iniciar-jornada'
      fullPath: '/motorista/iniciar-jornada'
      preLoaderRoute: typeof MotoristaIniciarJornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/historico': {
      id: '/motorista/historico'
      path: '/motorista/historico'
      fullPath: '/motorista/historico'
      preLoaderRoute: typeof MotoristaHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/foto': {
      id: '/motorista/foto'
      path: '/motorista/foto'
      fullPath: '/motorista/foto'
      preLoaderRoute: typeof MotoristaFotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/encerrar-jornada': {
      id: '/motorista/encerrar-jornada'
      path: '/motorista/encerrar-jornada'
      fullPath: '/motorista/encerrar-jornada'
      preLoaderRoute: typeof MotoristaEncerrarJornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/checklist': {
      id: '/motorista/checklist'
      path: '/motorista/checklist'
      fullPath: '/motorista/checklist'
      preLoaderRoute: typeof MotoristaChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/abastecimento': {
      id: '/motorista/abastecimento'
      path: '/motorista/abastecimento'
      fullPath: '/motorista/abastecimento'
      preLoaderRoute: typeof MotoristaAbastecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/veiculos': {
      id: '/gestor/veiculos'
      path: '/gestor/veiculos'
      fullPath: '/gestor/veiculos'
      preLoaderRoute: typeof GestorVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/motoristas': {
      id: '/gestor/motoristas'
      path: '/gestor/motoristas'
      fullPath: '/gestor/motoristas'
      preLoaderRoute: typeof GestorMotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/manutencoes': {
      id: '/gestor/manutencoes'
      path: '/gestor/manutencoes'
      fullPath: '/gestor/manutencoes'
      preLoaderRoute: typeof GestorManutencoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/solicitacoes': {
      id: '/fornecedor/solicitacoes'
      path: '/fornecedor/solicitacoes'
      fullPath: '/fornecedor/solicitacoes'
      preLoaderRoute: typeof FornecedorSolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/servicos': {
      id: '/fornecedor/servicos'
      path: '/fornecedor/servicos'
      fullPath: '/fornecedor/servicos'
      preLoaderRoute: typeof FornecedorServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/servico': {
      id: '/fornecedor/servico'
      path: '/fornecedor/servico'
      fullPath: '/fornecedor/servico'
      preLoaderRoute: typeof FornecedorServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/perfil': {
      id: '/fornecedor/perfil'
      path: '/fornecedor/perfil'
      fullPath: '/fornecedor/perfil'
      preLoaderRoute: typeof FornecedorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/orcamentos': {
      id: '/fornecedor/orcamentos'
      path: '/fornecedor/orcamentos'
      fullPath: '/fornecedor/orcamentos'
      preLoaderRoute: typeof FornecedorOrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/orcamento': {
      id: '/fornecedor/orcamento'
      path: '/fornecedor/orcamento'
      fullPath: '/fornecedor/orcamento'
      preLoaderRoute: typeof FornecedorOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/lancar-pecas': {
      id: '/fornecedor/lancar-pecas'
      path: '/fornecedor/lancar-pecas'
      fullPath: '/fornecedor/lancar-pecas'
      preLoaderRoute: typeof FornecedorLancarPecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/historico': {
      id: '/fornecedor/historico'
      path: '/fornecedor/historico'
      fullPath: '/fornecedor/historico'
      preLoaderRoute: typeof FornecedorHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/financeiro': {
      id: '/fornecedor/financeiro'
      path: '/fornecedor/financeiro'
      fullPath: '/fornecedor/financeiro'
      preLoaderRoute: typeof FornecedorFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/despesa': {
      id: '/fornecedor/despesa'
      path: '/fornecedor/despesa'
      fullPath: '/fornecedor/despesa'
      preLoaderRoute: typeof FornecedorDespesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/abastecer': {
      id: '/fornecedor/abastecer'
      path: '/fornecedor/abastecer'
      fullPath: '/fornecedor/abastecer'
      preLoaderRoute: typeof FornecedorAbastecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro-contratual': {
      id: '/admin/financeiro-contratual'
      path: '/admin/financeiro-contratual'
      fullPath: '/admin/financeiro-contratual'
      preLoaderRoute: typeof AdminFinanceiroContratualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecer/$veiculoId': {
      id: '/abastecer/$veiculoId'
      path: '/abastecer/$veiculoId'
      fullPath: '/abastecer/$veiculoId'
      preLoaderRoute: typeof AbastecerVeiculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/veiculos/$veiculoId': {
      id: '/gestor/veiculos/$veiculoId'
      path: '/$veiculoId'
      fullPath: '/gestor/veiculos/$veiculoId'
      preLoaderRoute: typeof GestorVeiculosVeiculoIdRouteImport
      parentRoute: typeof GestorVeiculosRoute
    }
    '/admin/financeiro/fornecedores': {
      id: '/admin/financeiro/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/financeiro/fornecedores'
      preLoaderRoute: typeof AdminFinanceiroFornecedoresRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/clientes/$empresaId': {
      id: '/admin/clientes/$empresaId'
      path: '/$empresaId'
      fullPath: '/admin/clientes/$empresaId'
      preLoaderRoute: typeof AdminClientesEmpresaIdRouteImport
      parentRoute: typeof AdminClientesRoute
    }
  }
}

interface AdminClientesRouteChildren {
  AdminClientesEmpresaIdRoute: typeof AdminClientesEmpresaIdRoute
}

const AdminClientesRouteChildren: AdminClientesRouteChildren = {
  AdminClientesEmpresaIdRoute: AdminClientesEmpresaIdRoute,
}

const AdminClientesRouteWithChildren = AdminClientesRoute._addFileChildren(
  AdminClientesRouteChildren,
)

interface AdminFinanceiroRouteChildren {
  AdminFinanceiroFornecedoresRoute: typeof AdminFinanceiroFornecedoresRoute
}

const AdminFinanceiroRouteChildren: AdminFinanceiroRouteChildren = {
  AdminFinanceiroFornecedoresRoute: AdminFinanceiroFornecedoresRoute,
}

const AdminFinanceiroRouteWithChildren = AdminFinanceiroRoute._addFileChildren(
  AdminFinanceiroRouteChildren,
)

interface GestorVeiculosRouteChildren {
  GestorVeiculosVeiculoIdRoute: typeof GestorVeiculosVeiculoIdRoute
}

const GestorVeiculosRouteChildren: GestorVeiculosRouteChildren = {
  GestorVeiculosVeiculoIdRoute: GestorVeiculosVeiculoIdRoute,
}

const GestorVeiculosRouteWithChildren = GestorVeiculosRoute._addFileChildren(
  GestorVeiculosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CredenciamentoRoute: CredenciamentoRoute,
  LoginRoute: LoginRoute,
  AbastecerVeiculoIdRoute: AbastecerVeiculoIdRoute,
  AdminClientesRoute: AdminClientesRouteWithChildren,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRouteWithChildren,
  AdminFinanceiroContratualRoute: AdminFinanceiroContratualRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  FornecedorAbastecerRoute: FornecedorAbastecerRoute,
  FornecedorDespesaRoute: FornecedorDespesaRoute,
  FornecedorFinanceiroRoute: FornecedorFinanceiroRoute,
  FornecedorHistoricoRoute: FornecedorHistoricoRoute,
  FornecedorLancarPecasRoute: FornecedorLancarPecasRoute,
  FornecedorOrcamentoRoute: FornecedorOrcamentoRoute,
  FornecedorOrcamentosRoute: FornecedorOrcamentosRoute,
  FornecedorPerfilRoute: FornecedorPerfilRoute,
  FornecedorServicoRoute: FornecedorServicoRoute,
  FornecedorServicosRoute: FornecedorServicosRoute,
  FornecedorSolicitacoesRoute: FornecedorSolicitacoesRoute,
  GestorManutencoesRoute: GestorManutencoesRoute,
  GestorMotoristasRoute: GestorMotoristasRoute,
  GestorVeiculosRoute: GestorVeiculosRouteWithChildren,
  MotoristaAbastecimentoRoute: MotoristaAbastecimentoRoute,
  MotoristaChecklistRoute: MotoristaChecklistRoute,
  MotoristaEncerrarJornadaRoute: MotoristaEncerrarJornadaRoute,
  MotoristaFotoRoute: MotoristaFotoRoute,
  MotoristaHistoricoRoute: MotoristaHistoricoRoute,
  MotoristaIniciarJornadaRoute: MotoristaIniciarJornadaRoute,
  MotoristaNotificacoesRoute: MotoristaNotificacoesRoute,
  MotoristaSolicitarRoute: MotoristaSolicitarRoute,
  MotoristaViagemRoute: MotoristaViagemRoute,
  AdminIndexRoute: AdminIndexRoute,
  FornecedorIndexRoute: FornecedorIndexRoute,
  GestorIndexRoute: GestorIndexRoute,
  MotoristaIndexRoute: MotoristaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
